version: '3'
services:
  java-app:
    build:
      context: ./java-docker
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db
    depends_on:
      - db
    networks:
      - curso-docker
  node-app:
    build:
      context: ./node-docker
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/code
    networks:
      - curso-docker
  db:
    build:
      context: ./postgres-docker
      dockerfile: Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - curso-docker
networks:
  curso-docker:
    driver: bridge
volumes:
  postgres_data: